import '../../public/style/reset.css';
import '../../public/style/globals.css';

export const metadata = {
  title: 'quick sync',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='zh-CN' translate='no'>
      <body>{children}</body>
    </html>
  );
}
