import '@/style/reset.css';
import '@/style/globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';

export const metadata = {
  title: 'quick sync',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='zh-CN' translate='no'>
      <body><AntdRegistry>{children}</AntdRegistry></body>
    </html>
  );
}
